## Bronze Layer

In [1]:
import pandas as pd
from pyspark.sql.functions import *

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 3, Finished, Available, Finished, False)

In [2]:
df = pd.read_parquet('abfss://eeabbd80-83ac-4257-b31b-56d4053059ef@onelake.dfs.fabric.microsoft.com/8c51827e-7f91-45cf-b889-fcb12b465856/Tables/ashish_bronze_trips/parquet')

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 4, Finished, Available, Finished, False)

In [3]:
df.head()

StatementMeta(, f7dd7de8-2208-47f4-82bf-1edb22687628, 5, Finished, Available, Finished, False)

,vendorID,lpepPickupDatetime,lpepDropoffDatetime,passengerCount,tripDistance,puLocationId,doLocationId,pickupLongitude,pickupLatitude,dropoffLongitude,...,paymentType,fareAmount,extra,mtaTax,improvementSurcharge,tipAmount,tollsAmount,ehailFee,totalAmount,tripType
0,2,2017-12-05 00:57:28,2017-12-05 01:01:51,1,0.60,41,74,NaN,NaN,NaN,...,2,5.0,0.0,0.5,0.3,0.00,0.0,NaN,5.80,1.0
1,2,2017-12-05 01:05:54,2017-12-05 01:13:09,1,0.88,74,75,NaN,NaN,NaN,...,1,6.5,0.0,0.5,0.3,1.46,0.0,NaN,8.76,1.0
2,2,2017-12-14 03:53:21,2017-12-14 04:09:13,1,7.54,75,148,NaN,NaN,NaN,...,2,22.0,0.0,0.5,0.3,0.00,0.0,NaN,22.80,1.0
3,2,2017-12-14 10:21:37,2017-12-14 10:27:50,1,1.34,75,263,NaN,NaN,NaN,...,2,6.5,0.0,0.5,0.3,0.00,0.0,NaN,7.30,1.0
4,2,2017-12-15 04:53:36,2017-12-15 05:04:41,1,2.66,75,159,NaN,NaN,NaN,...,1,10.5,0.0,0.5,0.3,0.00,0.0,NaN,11.30,1.0

In [4]:
df.shape

StatementMeta(, f7dd7de8-2208-47f4-82bf-1edb22687628, 6, Finished, Available, Finished, False)

(76513115, 23)

In [5]:
df.info()

StatementMeta(, f7dd7de8-2208-47f4-82bf-1edb22687628, 7, Finished, Available, Finished, False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76513115 entries, 0 to 76513114
Data columns (total 23 columns):
 #   Column                Dtype
---  ------                -----
 0   vendorID              int32
 1   lpepPickupDatetime    datetime64[ns]
 2   lpepDropoffDatetime   datetime64[ns]
 3   passengerCount        int32
 4   tripDistance          float64
 5   puLocationId          object
 6   doLocationId          object
 7   pickupLongitude       float64
 8   pickupLatitude        float64
 9   dropoffLongitude      float64
 10  dropoffLatitude       float64
 11  rateCodeID            int32
 12  storeAndFwdFlag       object
 13  paymentType           int32
 14  fareAmount            float64
 15  extra                 float64
 16  mtaTax                float64
 17  improvementSurcharge  object
 18  tipAmount             float64
 19  tollsAmount           float64
 20  ehailFee              float64
 21  totalAmount           float64
 22  tripType              float64
dtypes: datetime64[ns](2), float64(13), int32(4), object(4)
memory usage: 12.0+ GB

improvementSurcharge - object -> float

In [6]:
df.describe()

StatementMeta(, f7dd7de8-2208-47f4-82bf-1edb22687628, 8, Finished, Available, Finished, False)

,vendorID,lpepPickupDatetime,lpepDropoffDatetime,passengerCount,tripDistance,pickupLongitude,pickupLatitude,dropoffLongitude,dropoffLatitude,rateCodeID,paymentType,fareAmount,extra,mtaTax,tipAmount,tollsAmount,ehailFee,totalAmount,tripType
count,7.651312e+07,76513115,76513115,7.651312e+07,7.651312e+07,4.529961e+07,4.529961e+07,4.529961e+07,4.529961e+07,7.651312e+07,7.651312e+07,7.651312e+07,7.651312e+07,7.651312e+07,7.651312e+07,7.651312e+07,0.0,7.651312e+07,7.353796e+07
mean,1.795782e+00,2016-04-15 21:54:02.025723392,2016-04-15 22:13:01.502949376,1.377969e+00,2.905868e+00,-7.381626e+01,4.068677e+01,-7.382281e+01,4.068847e+01,1.102028e+00,1.528310e+00,1.242298e+01,3.511022e-01,4.874894e-01,1.146373e+00,1.233367e-01,NaN,1.480090e+01,1.023215e+00
min,1.000000e+00,2008-12-31 09:06:23,2008-12-31 10:02:33,0.000000e+00,0.000000e+00,-1.223996e+02,-4.075827e+01,-1.223996e+02,0.000000e+00,1.000000e+00,1.000000e+00,-8.900000e+02,-2.542000e+01,-4.950000e+01,-1.010000e+02,-8.000000e+01,NaN,-8.903000e+02,1.000000e+00
25%,2.000000e+00,2015-02-11 22:23:47,2015-02-11 22:35:41,1.000000e+00,1.050000e+00,-7.395879e+01,4.070238e+01,-7.396707e+01,4.070410e+01,1.000000e+00,1.000000e+00,6.500000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,NaN,7.850000e+00,1.000000e+00
50%,2.000000e+00,2016-02-11 19:55:49,2016-02-11 20:13:06,1.000000e+00,1.900000e+00,-7.394460e+01,4.074750e+01,-7.394422e+01,4.074999e+01,1.000000e+00,2.000000e+00,9.500000e+00,5.000000e-01,5.000000e-01,0.000000e+00,0.000000e+00,NaN,1.130000e+01,1.000000e+00
75%,2.000000e+00,2017-05-12 09:04:29,2017-05-12 09:25:50,1.000000e+00,3.620000e+00,-7.391581e+01,4.080458e+01,-7.390878e+01,4.079498e+01,1.000000e+00,2.000000e+00,1.500000e+01,5.000000e-01,5.000000e-01,1.890000e+00,0.000000e+00,NaN,1.780000e+01,1.000000e+00
max,2.000000e+00,2081-06-24 17:40:37,2081-06-24 18:42:47,9.000000e+00,8.005680e+03,7.393764e+01,4.341588e+01,0.000000e+00,4.811947e+01,9.900000e+01,5.000000e+00,1.044584e+04,6.795300e+02,8.291000e+01,2.017730e+03,7.999920e+03,NaN,9.899704e+05,2.000000e+00
std,4.031292e-01,NaN,NaN,1.059324e+00,3.227774e+00,2.962536e+00,1.632326e+00,2.870811e+00,1.581632e+00,6.917213e-01,5.229031e-01,1.086702e+01,4.121738e-01,8.483347e-02,2.649506e+00,1.498620e+00,NaN,1.144462e+02,1.505849e-01

Passenger Count -> 0

Max datetime -> 2081

All amts min -> -ve values

In [7]:
print("No of rows.",df.shape[0])
df.isnull().sum()

StatementMeta(, f7dd7de8-2208-47f4-82bf-1edb22687628, 9, Finished, Available, Finished, False)

No of rows. 76513115

vendorID                       0
lpepPickupDatetime             0
lpepDropoffDatetime            0
passengerCount                 0
tripDistance                   0
puLocationId            45299607
doLocationId            45299607
pickupLongitude         31213508
pickupLatitude          31213508
dropoffLongitude        31213508
dropoffLatitude         31213508
rateCodeID                     0
storeAndFwdFlag                0
paymentType                    0
fareAmount                     0
extra                          0
mtaTax                         0
improvementSurcharge    17047812
tipAmount                      0
tollsAmount                    0
ehailFee                76513115
totalAmount                    0
tripType                 2975151
dtype: int64

## Silver Layer

In [3]:
raw_df = df.copy()

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 5, Finished, Available, Finished, False)

In [9]:
raw_df.shape

StatementMeta(, f7dd7de8-2208-47f4-82bf-1edb22687628, 11, Finished, Available, Finished, False)

(76513115, 23)

### Convert Data types

In [10]:
df.dtypes

StatementMeta(, f7dd7de8-2208-47f4-82bf-1edb22687628, 12, Finished, Available, Finished, False)

vendorID                         int32
lpepPickupDatetime      datetime64[ns]
lpepDropoffDatetime     datetime64[ns]
passengerCount                   int32
tripDistance                   float64
puLocationId                    object
doLocationId                    object
pickupLongitude                float64
pickupLatitude                 float64
dropoffLongitude               float64
dropoffLatitude                float64
rateCodeID                       int32
storeAndFwdFlag                 object
paymentType                      int32
fareAmount                     float64
extra                          float64
mtaTax                         float64
improvementSurcharge            object
tipAmount                      float64
tollsAmount                    float64
ehailFee                       float64
totalAmount                    float64
tripType                       float64
dtype: object

In [4]:
df['improvementSurcharge'] = pd.to_numeric(df['improvementSurcharge'],errors='coerce')
#coerce convert invalid entry to null

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 6, Finished, Available, Finished, False)

In [5]:
categorical_columns = [
    'vendorID',
    'rateCodeID',
    'paymentType',
    'tripType'
]

df[categorical_columns] = df[categorical_columns].astype('string')

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 7, Finished, Available, Finished, False)

In [13]:
df.dtypes

StatementMeta(, f7dd7de8-2208-47f4-82bf-1edb22687628, 15, Finished, Available, Finished, False)

vendorID                string[python]
lpepPickupDatetime      datetime64[ns]
lpepDropoffDatetime     datetime64[ns]
passengerCount                   int32
tripDistance                   float64
puLocationId                    object
doLocationId                    object
pickupLongitude                float64
pickupLatitude                 float64
dropoffLongitude               float64
dropoffLatitude                float64
rateCodeID              string[python]
storeAndFwdFlag                 object
paymentType             string[python]
fareAmount                     float64
extra                          float64
mtaTax                         float64
improvementSurcharge           float64
tipAmount                      float64
tollsAmount                    float64
ehailFee                       float64
totalAmount                    float64
tripType                string[python]
dtype: object

In [14]:
# duplicates = df[df.duplicated()]

# duplicates.head()

StatementMeta(, f7dd7de8-2208-47f4-82bf-1edb22687628, 16, Finished, Available, Finished, False)

In [15]:
df_duplicates = df.duplicated(
    subset=[
        'vendorID',
        'lpepPickupDatetime',
        'lpepDropoffDatetime',
        'puLocationId',
        'doLocationId',
        'fareAmount',
        'passengerCount'
    ]
).sum()

print(df_duplicates)

StatementMeta(, f7dd7de8-2208-47f4-82bf-1edb22687628, 17, Finished, Available, Finished, False)

2326

### Droping Duplicates

In [8]:
df = df.drop_duplicates(
    subset=[
        'vendorID',
        'lpepPickupDatetime',
        'lpepDropoffDatetime',
        'puLocationId',
        'doLocationId',
        'fareAmount',
        'passengerCount'
    ]
)

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 10, Finished, Available, Finished, False)

 ### Handling Null values

In [6]:
drop_columns = [
    'ehailFee',
    'pickupLatitude',
    'pickupLongitude',
    'dropoffLatitude',
    'dropoffLongitude'
]

df = df.drop(columns=drop_columns)

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 8, Finished, Available, Finished, False)

In [7]:
df = df.dropna(subset=['puLocationId', 'doLocationId'])

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 9, Finished, Available, Finished, False)

In [9]:
print(df.columns)

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 11, Finished, Available, Finished, False)

Index(['vendorID', 'lpepPickupDatetime', 'lpepDropoffDatetime',
       'passengerCount', 'tripDistance', 'puLocationId', 'doLocationId',
       'rateCodeID', 'storeAndFwdFlag', 'paymentType', 'fareAmount', 'extra',
       'mtaTax', 'improvementSurcharge', 'tipAmount', 'tollsAmount',
       'totalAmount', 'tripType'],
      dtype='object')

### Validity rules
1. numeric values > 0 (passengerCount', 'tripDistance', 'fareAmount', 'extra',
       'mtaTax', 'improvementSurcharge', 'tipAmount', 'tollsAmount',
       'totalAmount')

2. Limit max(datetime) to current
3. puLocationId and doLoacationId is not null
4. Drop off Time > Pick up time

In [10]:
numeric_columns = [
    'passengerCount',
    'tripDistance',
    'fareAmount',
    'extra',
    'mtaTax',
    'improvementSurcharge',
    'tipAmount',
    'tollsAmount',
    'totalAmount'
]

for col in numeric_columns:
    df[col] = df[col].abs()

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 12, Finished, Available, Finished, False)

In [11]:
df = df[
    (df["tripDistance"] > 0) &
    (df["totalAmount"] > 0) &
    (df["passengerCount"] > 0)
]

print("After invalid values removed:", df.shape[0])

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 13, Finished, Available, Finished, False)

After invalid values removed: 30749635

### Limit to current date and time.

In [12]:
current_date = pd.Timestamp.now()

df = df[df['lpepPickupDatetime'] <= current_date]

df = df[df['lpepDropoffDatetime'] <= current_date]

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 14, Finished, Available, Finished, False)

### Drop off time > Pick up time

In [13]:
df = df[df['lpepDropoffDatetime'] > df['lpepPickupDatetime']]

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 15, Finished, Available, Finished, False)

In [14]:
print(df.shape)

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 16, Finished, Available, Finished, False)

(30746774, 18)

## Column Name

In [15]:
rename_columns = {
    'vendorID': 'vendor_id',
    'lpepPickupDatetime': 'pickup_datetime',
    'lpepDropoffDatetime': 'dropoff_datetime',
    'passengerCount': 'passenger_count',
    'tripDistance': 'trip_distance',
    'rateCodeID': 'rate_code_id',
    'storeAndFwdFlag': 'store_and_fwd_flag',
    'puLocationId': 'pickup_location_id',
    'doLocationId': 'dropoff_location_id',
    'paymentType': 'payment_type',
    'fareAmount': 'fare_amount',
    'mtaTax': 'mta_tax',
    'tipAmount': 'tip_amount',
    'tollsAmount': 'tolls_amount',
    'improvementSurcharge': 'improvement_surcharge',
    'totalAmount': 'total_amount',
    'tripType': 'trip_type'
}
df = df.rename(columns=rename_columns)

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 17, Finished, Available, Finished, False)

In [16]:
df.columns

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 18, Finished, Available, Finished, False)

Index(['vendor_id', 'pickup_datetime', 'dropoff_datetime', 'passenger_count',
       'trip_distance', 'pickup_location_id', 'dropoff_location_id',
       'rate_code_id', 'store_and_fwd_flag', 'payment_type', 'fare_amount',
       'extra', 'mta_tax', 'improvement_surcharge', 'tip_amount',
       'tolls_amount', 'total_amount', 'trip_type'],
      dtype='object')

In [17]:
silver_df = df.copy()

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 19, Finished, Available, Finished, False)

### Changes in the dataset.

In [18]:
print(
    f"{raw_df.shape[0]} rows and {raw_df.shape[1]} columns\n"
    f"{silver_df.shape[0]} rows and {silver_df.shape[1]} columns"
)

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 20, Finished, Available, Finished, False)

76513115 rows and 23 columns
30746774 rows and 18 columns

### Save the Silver table

In [19]:
silver_spark_df = spark.createDataFrame(silver_df)
silver_spark_df.write.mode("overwrite").saveAsTable(
    "ashish_silver_trips"
)

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 21, Finished, Available, Finished, False)

In [20]:
%%sql
Select * from ashish_silver_trips limit 10;

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 22, Finished, Available, Finished, False)

### Creating Date Dimension Table.

Extract dates

In [21]:
pickup_dates = silver_df['pickup_datetime'].dt.date

dropoff_dates = silver_df['dropoff_datetime'].dt.date

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 23, Finished, Available, Finished, False)

In [22]:
all_dates = pd.concat([
    pickup_dates,
    dropoff_dates
]).drop_duplicates().reset_index(drop=True)

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 24, Finished, Available, Finished, False)

In [23]:
dim_date = pd.DataFrame({
    'date': pd.to_datetime(all_dates)
})

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 25, Finished, Available, Finished, False)

In [24]:
dim_date['date_key'] = dim_date['date'].dt.strftime('%Y%m%d').astype(int)

dim_date['year'] = dim_date['date'].dt.year

dim_date['quarter'] = dim_date['date'].dt.quarter

dim_date['month'] = dim_date['date'].dt.month

dim_date['month_name'] = dim_date['date'].dt.month_name()

dim_date['day'] = dim_date['date'].dt.day

dim_date['day_name'] = dim_date['date'].dt.day_name()

dim_date['weekday'] = dim_date['date'].dt.weekday

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 26, Finished, Available, Finished, False)

In [25]:
#Re-ordering the columns
dim_date = dim_date[
    [
        'date_key',
        'date',
        'year',
        'quarter',
        'month',
        'month_name',
        'day',
        'day_name',
        'weekday'
    ]
]

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 27, Finished, Available, Finished, False)

In [26]:
dim_date.head()

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 28, Finished, Available, Finished, False)

,date_key,date,year,quarter,month,month_name,day,day_name,weekday
0,20171205,2017-12-05,2017,4,12,December,5,Tuesday,1
1,20171214,2017-12-14,2017,4,12,December,14,Thursday,3
2,20171215,2017-12-15,2017,4,12,December,15,Friday,4
3,20171201,2017-12-01,2017,4,12,December,1,Friday,4
4,20171202,2017-12-02,2017,4,12,December,2,Saturday,5

In [27]:
dim_date.info()

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 29, Finished, Available, Finished, False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1103 entries, 0 to 1102
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date_key    1103 non-null   int64
 1   date        1103 non-null   datetime64[ns]
 2   year        1103 non-null   int32
 3   quarter     1103 non-null   int32
 4   month       1103 non-null   int32
 5   month_name  1103 non-null   object
 6   day         1103 non-null   int32
 7   day_name    1103 non-null   object
 8   weekday     1103 non-null   int32
dtypes: datetime64[ns](1), int32(5), int64(1), object(2)
memory usage: 56.1+ KB

In [28]:
dim_date_spark = spark.createDataFrame(dim_date)

dim_date_spark.write.mode("overwrite").saveAsTable(
    "ashish_gold_dim_date"
)

StatementMeta(, 9ba2bb58-121e-465c-af2d-4377152d88a3, 30, Finished, Available, Finished, False)